# docker-compose.dev.yml
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ecommerce-backend-dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Mount source code for live reloading
      - .:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - ecommerce-dev-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  ecommerce-dev-network:
    driver: bridge